name: CI -> Deploy to My website
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - name: Upload from public_html via FTP
              uses: airvzxf/ftp-deployment-action@latest
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  user: ${{ secrets.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  local_dir: ''
                  delete: 'false'
