name: CI -> Deploy to My website
on: [push]
jobs:
    - upload:
          - name: Upload build to hosting environment
            uses: Atyn/Simple-SFTP
            with:
                url: sftp://USERNAME:PASSWORD@example.com/remote-directory
                local-directory: build-output
